config/routes.rb
Rails.application.routes.draw do
  root 'countries#index'
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    response = HTTParty.get("http://api.fixer.io/latest?base=#{@country.currency_code}")
    @to_value = response['rates']["#{@country.to_currency}"]
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :code, :currency_code, :to_currency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :country_name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :country_code %>
  </div>

  <div class="field">
    <%= form.label :currency_code %>
    <%= form.text_field :currency_code, id: :country_currency_code %>
  </div>

  <div class="field">
    <%= form.label :to_currency %>
    <%= form.text_field :to_currency, id: :country_to_currency %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country, class: 'btn btn-success' %>
<%= link_to 'Back', countries_path, class: 'btn btn-success' %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Currency code</th>
      <th>To currency</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= link_to country.name, country, class: 'btn btn-success' %></td>
        <td><%= country.code %></td>
        <td><%= country.currency_code %></td>
        <td><%= country.to_currency %></td>
        <td><%= link_to 'Edit', edit_country_path(country), class: 'btn btn-warning' %>
            <%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn
        btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path, class: 'btn btn-warning' %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path, class: 'btn btn-success' %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @country.name %></h2>
</p>

<p>
  <strong>Currency code:</strong>
  <%= @country.currency_code %>
</p>

<p>
  <strong><%= @country.to_currency %></strong>
  <%= @to_value %>
</p>

<%= link_to 'Edit', edit_country_path(@country), class: 'btn btn-warning' %>
<%= link_to 'Back', countries_path, class: 'btn btn-success' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaCurrencyConverter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>